### ISSUE TITLE
describe "identify" spec is failing due to a missing /n

### ISSUE THREAD

**Issue by mmclead** [markevans/dragonfly#321]
when running specs on jruby 1.7.10 the describe "identify" spec fails.  

The failure looks like this:

```
1) a configured imagemagick app identify gives the output of the command line
     Failure/Error: image.identify("-format %h").should == "355\n"
       expected: "355\n"
            got: "355" (using ==)
       Diff:
     # ./spec/dragonfly/image_magick/plugin_spec.rb:127:in `(root)'
```
